"""Add RBAC and mentor fields

Revision ID: ec32b160f46a
Revises: 
Create Date: 2025-10-02 20:40:04.564915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec32b160f46a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skillrequest')
    op.drop_table('mentorcompatibility')
    # op.drop_table('skill')
    op.drop_table('message')
    # op.drop_table('mentorshipsession')
    op.drop_table('matchingsession')
    # op.drop_table('review')
    op.drop_table('skillassessment')
    op.drop_table('userpreferences')
    op.add_column('mentorprofile', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('mentorprofile', sa.Column('max_students', sa.Integer(), nullable=True))
    op.add_column('mentorprofile', sa.Column('preferred_learning_styles', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('role', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('learning_goal', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('preferred_language', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('time_zone', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('learning_style', sa.String(), nullable=True))
    op.drop_column('userprofile', 'is_mentor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('is_mentor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('userprofile', 'learning_style')
    op.drop_column('userprofile', 'time_zone')
    op.drop_column('userprofile', 'preferred_language')
    op.drop_column('userprofile', 'learning_goal')
    op.drop_column('userprofile', 'role')
    op.drop_column('mentorprofile', 'preferred_learning_styles')
    op.drop_column('mentorprofile', 'max_students')
    op.drop_column('mentorprofile', 'rating')
    op.create_table('userpreferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('learning_style', postgresql.ENUM('VISUAL', 'AUDITORY', 'KINESTHETIC', 'READING_WRITING', name='learningstyle'), autoincrement=False, nullable=False),
    sa.Column('communication_style', postgresql.ENUM('DIRECT', 'SUPPORTIVE', 'ANALYTICAL', 'EXPRESSIVE', name='communicationstyle'), autoincrement=False, nullable=False),
    sa.Column('preferred_session_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_time_zones', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('learning_goals', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_skill_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel'), autoincrement=False, nullable=False),
    sa.Column('target_skill_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel'), autoincrement=False, nullable=False),
    sa.Column('preferred_mentor_experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_age_range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('budget_range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extroversion_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patience_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('technical_focus_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creativity_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], name=op.f('userpreferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userpreferences_pkey'))
    )
    op.create_table('skillassessment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel'), autoincrement=False, nullable=False),
    sa.Column('target_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('learning_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('estimated_timeline', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], name=op.f('skillassessment_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skillassessment_pkey'))
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewee_id'], ['userprofile.id'], name=op.f('review_reviewee_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['userprofile.id'], name=op.f('review_reviewer_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['mentorshipsession.id'], name=op.f('review_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_pkey'))
    )
    op.create_table('matchingsession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_compatibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('personality_compatibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('availability_compatibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('budget_compatibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('match_reasoning', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('potential_challenges', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('success_prediction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['userprofile.id'], name=op.f('matchingsession_mentee_id_fkey')),
    sa.ForeignKeyConstraint(['mentor_id'], ['userprofile.id'], name=op.f('matchingsession_mentor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('matchingsession_pkey'))
    )
    op.create_table('mentorshipsession',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('mentorshipsession_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='sessionstatus'), autoincrement=False, nullable=False),
    sa.Column('meeting_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['userprofile.id'], name='mentorshipsession_learner_id_fkey'),
    sa.ForeignKeyConstraint(['mentor_id'], ['userprofile.id'], name='mentorshipsession_mentor_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='mentorshipsession_skill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mentorshipsession_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_type', postgresql.ENUM('TEXT', 'FILE', 'VIDEO_CALL', name='messagetype'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['userprofile.id'], name=op.f('message_recipient_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['userprofile.id'], name=op.f('message_sender_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['mentorshipsession.id'], name=op.f('message_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('message_pkey'))
    )
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('PROGRAMMING', 'DESIGN', 'LANGUAGES', 'BUSINESS', 'MARKETING', 'DATA_SCIENCE', 'WRITING', 'MUSIC', 'PHOTOGRAPHY', 'OTHER', name='skillcategory'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proficiency_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['userprofile.id'], name=op.f('skill_mentor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_table('mentorcompatibility',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teaching_style', postgresql.ENUM('DIRECT', 'SUPPORTIVE', 'ANALYTICAL', 'EXPRESSIVE', name='communicationstyle'), autoincrement=False, nullable=False),
    sa.Column('specialization_areas', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mentoring_approach', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('available_time_slots', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_mentees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_mentees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_mentee_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('industry_experience', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_mentees_mentored', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['userprofile.id'], name=op.f('mentorcompatibility_mentor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mentorcompatibility_pkey'))
    )
    op.create_table('skillrequest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('PROGRAMMING', 'DESIGN', 'LANGUAGES', 'BUSINESS', 'MARKETING', 'DATA_SCIENCE', 'WRITING', 'MUSIC', 'PHOTOGRAPHY', 'OTHER', name='skillcategory'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferred_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('budget_range', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['userprofile.id'], name=op.f('skillrequest_learner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skillrequest_pkey'))
    )
    # ### end Alembic commands ###
